version: '3'

services:
  test:
    image: proxy-tunnel:latest
    container_name: proxy-tunnel
#    network_mode: host  # 在服务器上部署时建议使用 host ，同时屏蔽下面的 ports
    ports:
      - "30000:30000"
      - "30100-30200:30100-30200"
    environment:
      # 自行配置 redis 相关环境变量
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_PASSWORD
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  db:
    external: true