version: '3'

services:
  test:
    image: proxy-tunnel:latest
    container_name: proxy-tunnel
#    network_mode: host
    ports:
      - "30000:30000"
      - "30100-30200:30100-30200"
    environment:
      - REDIS_HOST=172.20.0.2
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=XkNpx4Izc!T9uQ1smFd%WusBkp6P6XJC
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  db:
    external: true