name: Mirror and run GitLab CI

on: [push, delete]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "http://git.tianjiyunke.com/liuyang/proxy-tunnel"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "git.tianjiyunke.com"
        GITLAB_USERNAME: "believel.y@qq.com"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_PROJECT_ID: "128"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}